# Site
name: 'Women In Tech 泛宇宙科技姐妹'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/Option 5a.png'
favicon: 'assets/images/Option 5a.png'
baseurl: ''
disqus: 'demowebsite'
email: '@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    sal:
      name:           Sal
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    泛宇宙小编:
      name:           泛宇宙小编
      site:           https://mp.weixin.qq.com/s?__biz=MzU5ODAzMzc5NQ==&mid=2247483800&idx=1&sn=688b58842c28b02f57aa3511e4542a63&chksm=fe4b1574c93c9c62e0be32e5dfdf3d75a51b653b7ce99a32c188cc116004e12da0da20871986&token=889979630&lang=zh_CN#rd
      avatar:         /assets/images/Option 5b.png
      bio:            "这里泛宇宙小编~"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
